### ISSUE TITLE
Getting this error after installation.

### ISSUE THREAD

**Issue by markmadlangbayan** [scrubs767/GitStash#1]
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at GitWrapper.GitStashItem..ctor(Stash s)
   at GitWrapper.GitStashWrapper.get_Stashes()
   at GitStash.ViewModels.StashesViewModel.get_Stashes()
   at GitStash.Sections.StashesSection.Initialize(Object sender, SectionInitializeEventArgs e) in C:\Users\scrub\Source\Repos\GitStash\GitStash\Sections\StashesSection.cs:line 36
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by scrubs767** [comment]
Can you give me the version of visual studio and Gitstash as reported from Tools->About Microsoft Visual Studio. The Git stash version will be located in the top list box in the middle of the page.

**Comment by markmadlangbayan** [comment]
Here you go...  Thanks!

Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

**Comment by scrubs767** [comment]
And the version of Git stash as reported by the same window?

**Comment by markmadlangbayan** [comment]
GitStash Extension Stash   1.0
GitStash Visual Studio Extension Detailed Info

**Comment by scrubs767** [comment]
Yes, Unfortunately grab the latest version, which is 0.7. The version you have was uploaded with the wrong version number and is compiled against older SDK libraries that will not work with VS 2015 update 1. Please let me know

**Comment by markmadlangbayan** [comment]
Is there something you want me to check for you?

**Comment by scrubs767** [comment]
No, just uninstall and grab the latest version of the extension which is 0.7, restart VS and try it, that should fix your problems.

**Comment by markmadlangbayan** [comment]
Sorry, I'm still getting the same error.

GitStash on About Microsoft Visual Studio is 1.0.

Under Tools -> Extensions and Updates -> Installed.  The GitStash version is 0.7.

**Comment by Rwing** [comment]
me too, but my error information as follow:
System.MissingMethodException: Method not found: 'Void GitStash.ViewModels.RecommendedActionsViewModel..ctor(GitWrapper.IGitStashWrapper, TeamExplorer.Common.ITeamExplorerBase)'.
   at GitStash.Sections.RecommendedActionsSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

My environment:
win7 x64
vs2015 enterprise update1
GitStash 0.7
and I also installed vs2013

**Comment by scrubs767** [comment]
is there a .git directory in the top level of the project?

**Comment by pachman** [comment]
After git stash command
http://joxi.ru/D2PDKpdsdw85B2

**Comment by scrubs767** [comment]
I've uploaded a new version that adds some logging where this error is happening, This can be seen by looking in your output window and selecting the output from Git Stash. This should be available to look at after the Git stash page is opened.

**Comment by scrubs767** [comment]
I'm going to close this issue because you have not responded, if you have any more information please don't hesitate to post it again.
